spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  messages:
    encoding: UTF-8
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  # thymeleaf 配置
  thymeleaf:
    cache: false

# 1、mybatis-plus 配置
# 2、https://github.com/baomidou/mybatis-plus
mybatis-plus:
  type-aliases-package: run.hxtia.workbd.pojo
  configuration:
    use-generated-keys: true
  global-config:
    db-config:
      id-type: auto

springfox:
  documentation:
    swagger-ui:
      enabled: true
